language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.4.0
  - 2.3.3
  - 2.1.9
  - 2.0

bundler_args: "--without documentation --path bundle"

before_install:
  - git fetch --depth=1000000
  - gem install bundler

after_install:
  - rake install

script:
  # Tests use real git commands
  - git config --global user.email "danger@example.com"
  - git config --global user.name "Danger McShane"
  - bundle exec rubocop lib
  - bundle exec rake spec
  - bundle exec danger --verbose
  - bundle exec danger init --mousey --impatient

